module.exports = {
    SOCIT: 'SOCIT',
    SOCITED: 'SOCITED',
    GOT_SOCITS: 'GOT_SOCITS',

    GOT_CURRENT_USER: 'GOT_CURRENT_USER',
    GOT_USERS: 'GOT_USERS',

    FOLLOW: 'FOLLOW',
    FOLLOWED: 'FOLLOWED',

    UNFOLLOW: 'UNFOLLOW',
    UNFOLLOWED: 'UNFOLLOWED'
};
